### ISSUE TITLE
it seems great! but how can I use it?

### ISSUE THREAD

**Issue by children1987** [Yiling-J/django-admin-tree#1]

**Comment by children1987** [comment]
@Yiling-J Do you have a demo?

**Comment by Yiling-J** [comment]
@children1987 Did you find how to use? Also this project is very simple, if you have thousands of nodes, or you need some fancy tree traversal or search functions, this project may not suitable for you.

**Comment by children1987** [comment]
@Yiling-J Yes, maybe you are right, I choose mptt in the end. Thank you all the same!
